set_property PACKAGE_PIN M19 [get_ports a]
set_property PACKAGE_PIN M20 [get_ports b]
set_property PACKAGE_PIN M15 [get_ports c]
set_property IOSTANDARD LVCMOS33 [get_ports a]
set_property IOSTANDARD LVCMOS33 [get_ports b]
set_property IOSTANDARD LVCMOS33 [get_ports c]
